"""empty message

Revision ID: 46146aa76241
Revises: 9346dd25213e
Create Date: 2020-07-16 19:27:05.205768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46146aa76241'
down_revision = '9346dd25213e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.add_column('order', sa.Column('payment_details', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'payment_details')
    op.drop_column('order', 'is_paid')
    # ### end Alembic commands ###
